package model;
// Generated 02/07/2017 17:57:35 by Hibernate Tools 4.3.1



/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private ClientesId id;
     private Combustivel combustivel;
     private String nome;
     private String cpf;
     private String email;
     private String telefone;

    public Clientes() {
    }

	
    public Clientes(ClientesId id, Combustivel combustivel) {
        this.id = id;
        this.combustivel = combustivel;
    }
    public Clientes(ClientesId id, Combustivel combustivel, String nome, String cpf, String email, String telefone) {
       this.id = id;
       this.combustivel = combustivel;
       this.nome = nome;
       this.cpf = cpf;
       this.email = email;
       this.telefone = telefone;
    }
   
    public ClientesId getId() {
        return this.id;
    }
    
    public void setId(ClientesId id) {
        this.id = id;
    }
    public Combustivel getCombustivel() {
        return this.combustivel;
    }
    
    public void setCombustivel(Combustivel combustivel) {
        this.combustivel = combustivel;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }




}


