package model;
// Generated 02/07/2017 17:57:35 by Hibernate Tools 4.3.1



/**
 * ClientesId generated by hbm2java
 */
public class ClientesId  implements java.io.Serializable {


     private int id;
     private int combustivelId;

    public ClientesId() {
    }

    public ClientesId(int id, int combustivelId) {
       this.id = id;
       this.combustivelId = combustivelId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getCombustivelId() {
        return this.combustivelId;
    }
    
    public void setCombustivelId(int combustivelId) {
        this.combustivelId = combustivelId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClientesId) ) return false;
		 ClientesId castOther = ( ClientesId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getCombustivelId()==castOther.getCombustivelId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getCombustivelId();
         return result;
   }   


}


