package model;
// Generated 02/07/2017 17:57:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Combustivel generated by hbm2java
 */
public class Combustivel  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Set clienteses = new HashSet(0);

    public Combustivel() {
    }

    public Combustivel(String nome, Set clienteses) {
       this.nome = nome;
       this.clienteses = clienteses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set clienteses) {
        this.clienteses = clienteses;
    }




}


